email_notification:
  emails: dgirdyuk@intermedia.net
graphyte:
  host: example.com
  port: '456'
urls:
  token_url: https://login.intermedia.net/user/connect/token
  user_presence_ulr: https://api.intermedia.net/messaging/v1/presence/accounts/_me/users/
  subscribe_url: https://api.intermedia.net/messaging/v1/subscriptions/accounts/_me/users/_all
testing:
  client_id: cNkAQFOJHE6aLCVVWnZPw
  client_secret: lKV5ALCpsZ6salt4j1qUqm6t3VEGxsKIzRLwxSx0LXs
  hp_user_uid: d7882566-727a-42df-873d-3815277056ed
  client_resource: a8f50e3e-c8de-45f3-80e5-f73398f38a95